# Generated by Django 2.1.2 on 2021-06-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Home', '0002_cooler'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('address', models.TextField()),
                ('foodtype', models.TextField()),
                ('photo', models.ImageField(upload_to='food_images')),
            ],
        ),
    ]
